### ISSUE TITLE
Update data Spring 2023

### ISSUE THREAD

**Issue by r-erd** [drcicero/beautiful-tucan#23]
Hi, 

would it be possible to update the data on the website again, so that it can be used to plan for the next semester?

thanks in advance

**Comment by drcicero** [comment]
Thanks for asking :) I ran the script again today, you can find the results here:
https://www.student.informatik.tu-darmstadt.de/~dr85nixo/beautiful-tucan/index.html

**Comment by r-erd** [comment]
Thanks a lot!
