### ISSUE TITLE
update data for spring 2024

### ISSUE THREAD

**Issue by r-erd** [drcicero/beautiful-tucan#27]
Hi,

it's me again :)

can you update the data on the website again, so that it can be used to plan for the next semester?

thanks in advance!

**Comment by drcicero** [comment]
Hi, I updated the website. Sadly, some (new?) courses have no credit points associated in inferno yet. I hope somebody enters them eventually, although one can often have a rough guess what the CP would be depending on whether its another seminar, a praktikum, or a course, etc.

And the issue with the regulations still exists, so there's still no explicit list for Bachelor/Master PO 2023, and one should look at the Bachelor/Master PO 2015 instead. (Although I suppose tucan doesnt really tell you which POs these courses belong to either so I assume it continues to be the case that almost all courses are offered in all POs...)

Let me know, if beautiful-tucan still helps nevertheless :)

**Comment by r-erd** [comment]
Thansk! It's still very helpful, especially for quickly checking if a set of courses overlaps, and I was asking on behalf of some other students too
