### ISSUE TITLE
Calendar export broken

### ISSUE THREAD

**Issue by pkwagner** [drcicero/beautiful-tucan#6]
Clicking the calendar export button generates following (obviously invalid) iCal file:

```
blob:http://<host>/bddeae66-d5fa-48b2-b898-438cb532d95c
```

Opening this URL manually in a web browser afterwards triggers the actual download. The workaround just takes a few seconds, so it's really not a super-urgent issue. Just wanted to document it here.

**Comment by drcicero** [comment]
For me it generates "data:text/calendar;charset=utf-8,BEGIN..." links. Both on https://www.student.informatik.tu-darmstadt.de/~dr85nixo/beautiful-tucan/ and https://www.d120.de/semesterplan . And if I click on them it the download starts. Maybe that is different when using moment.js to generate the ical files? I don't know anything about moment.js :)

**Comment by pkwagner** [comment]
Just verified it with your links, these work for me as well. Then it's only a problem with my local setup I guess :)
